baseURL: "https://ewaroza.github.io/sparta/"
title: Sparta
paginate: 8
# theme: hugo-primer
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sparta
  description: 'Sparta description'
  author: Spartanin
  # author: ["Me", "You"] # multiple authors

  ShowReadingTime: true
  ShowShareButtons: false
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
    favicon: ''

  label:
    text: "Home"
    icon: /sparta/apple-touch-icon.png
    iconHeight: 35


  # home-info mode
  homeInfoParams:
    Title: "Thermopylae in Modern Polish Culture ğŸ—¡ï¸"
    Content: >
     Thermopylae is extrememely important in Poland. More important than anything else. Tutaj jeszcze trzeba coÅ› napisaÄ‡, Å¼eby byÅ‚ dobry wstÄ™p. WstÄ™p nie musi byÄ‡ dÅ‚ugi - moÅ¼e byÄ‡ krÃ³tki. Grunt, Å¼eby zdania byÅ‚y Å‚adnie zredagowane. O, a tutaj jeszcze jedno zdanie, Å¼eby sprawdziÄ‡, jak ukÅ‚adajÄ… siÄ™ linijki. Chyba nieÅºle. 


